steps:
- uses: actions/checkout@v2
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '6.0.x'
    include-prerelease: true
- run: dotnet pack .\src\VueCliMiddleware\VueCliMiddleware.csproj -c Release --output .\src\nupkgs
